// speedrun/src/components/Header.tsx
import React from 'react';
import "../css/Header.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Link } from "react-router-dom";

const Header = () => {
    return (
        <header>
            <nav className="navbar navbar-expand-lg">
                <div className="container">
                    <a className="navbar-brand" href="/">
                        <div className="logo">
                            <img src="https://www.speedrun.com/images/logo-white.png" alt="logo" />
                        </div>
                    </a>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                            <li className="nav-item">
                                <Link className="nav-link" to={'/games'}>Games</Link> 
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link" to={'/'}>News</Link>
                            </li>
                            <li className="navbar-item">
                                <Link className="nav-link" to={'/'}>About</Link>
                            </li>
                            <li className="navbar-item" v-if="!isAuth">
                                <Link className="nav-link" to={'/'}>Log in</Link>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    )
}

export default Header;

// frontend/src/components/main/Header.vue
<template>
  <div>
    <header>
      <nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
                  data-target="#collapse-target">
            <span class="navbar-toggler-icon"></span>
          </button>
          <router-link class="navbar-brand" :to="{name: 'home'}">
            <img src="https://i.pinimg.com/736x/da/c8/0f/dac80fbfa765803b4bca39cf7aa5b0b7.jpg" alt="Logo"
                 width="50"
                 height="44" class="img-fluid rounded-circle">
          </router-link>

          <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav ">
              <li class="nav-item">
                <router-link class="nav-link active" :to="{name: 'home'}" aria-current="page">Главная</router-link>
              </li>
              <li class="nav-item">
                <router-link class="nav-link" :to="{name:'Price'}">Цены</router-link>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Контакты</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </div>
</template>

<script>
export default {
  name: "Header"
}
</script>

<style scoped>

</style>
