// fitness_center/frontend/src/App.tsx
import React from 'react';
import Footer from "./components/footer/Footer";
import {Header} from "./components/header/Header";
import {Body} from './components/body/Body';

function App() {
    return (
        <div className="App">
            <Header/>
            <Body/>
            <Footer/>
        </div>
    )
}

export default App;

// lab2/src/App.vue
<template>
  <div id="app">
    <header-vue/>
    <router-view/>
    <footer-vue/>
  </div>

</template>


<script>
import HeaderVue from "./components/HeaderVue.vue"
import FooterVue from "./components/FooterVue.vue"


export default {
  components: {
    HeaderVue,
    FooterVue
  }

}

export class App {
}


</script>

<style lang="scss">
html, body{
  background-color: black;
}



</style>
