// lab2/frontend/src/App.vue
<template>
  <div id="app">
    <Header></Header>

    <main>
      <router-view/>
    </main>

    <Footer></Footer>
  </div>
</template>

<script>


import Footer from "@/components/Main/Footer";
import Header from "@/components/Main/Header";

export default {
  components: {Header, Footer}
}

</script>

<style>

</style>

// fitness_center/frontend/src/App.tsx
import React from 'react';
import Footer from "./components/footer/Footer";
import {Header} from "./components/header/Header";
import {Body} from './components/body/Body';

function App() {
    return (
        <div className="App">
            <Header/>
            <Body/>
            <Footer/>
        </div>
    )
}

export default App;
